name: Create auth.json

on: [push]

jobs:
  create-auth-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "auth.json"
          json: ${{ secrets.REVIEWER_ACCESS }}

      - run: npm run format
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
         commit_message: Create auth.json
         branch: ${{ github.head_ref }}
